### ISSUE TITLE
Map NULL objects

### ISSUE THREAD

**Issue by stesvis** [mark-gerarts/automapper-plus#13]
Hi, in this case:
`$dto = $mapper->map($john, EmployeeDto::class);`

if $john is null, the mapper throws an exception:

> "No mapping registered for converting an instance of class AutoMapperPlus\\AutoMapper into one of App\\DTOs\\EmployeeDTO"

Shouldn't it just set $dto to NULL as well?

**Comment by mark-gerarts** [comment]
Hi, that's a valid point. I hadn't given this any thought yet before. I've submitted a commit (& release) which changes this!

**Comment by stesvis** [comment]
Thanks!
