### ISSUE TITLE
How to handle support for mapping to stdClass

### ISSUE THREAD

**Issue by djmattyg007** [mark-gerarts/automapper-plus#3]
PHPStan has configuration for something it calls "object crates". These are classes that are like stdClass, that just accept whatever you read and write to them by way of __get() and __set().

I'd lile to suggest that the best way to support mapping to stdClass would be a generic system such as this, where you configure a destination class as an object crate, and everything is just written as-is. This makes it easy to extend when integrating it into frameworks and other dynamic code.

**Comment by mark-gerarts** [comment]
I'll definitely look into this, and how it's implemented in PHPStan. Thanks for the suggestion!

**Comment by smoelker** [comment]
Any progress on adding this feature?

**Comment by mark-gerarts** [comment]
I haven't started on this yet, as it looks it might take some time to do it right. I'll look into it come next week, since I'm a bit busy this week (holidays).

**Comment by mark-gerarts** [comment]
This is available as of release 1.1.0. I'm closing this, but feel free to reopen / create a new isue if you encounter problems :)
