### ISSUE TITLE
Copy values rather than create a new instance?

### ISSUE THREAD

**Issue by tommyiraone** [mark-gerarts/automapper-plus#49]
How do I copy values from a source object to an existing destination object rather than create a new one?

maybe like..
$mapper->map($sourceObject, $destinationObject) ??

**Comment by mark-gerarts** [comment]
Hi @tommyiraone. Which version are you using? In 1.x you can do the following:

```php
$mapper->mapToObject($sourceObject, $destinationObject);
```

In 2.x (beta) this is part of the `map` function, meaning your example would work.

**Comment by tommyiraone** [comment]
I'm using 1.x
sorry for that, I think I have missed that one.

Thank you.
