### ISSUE TITLE
Typed properties break mapping operations

### ISSUE THREAD

**Issue by shadowhand** [mark-gerarts/automapper-plus#58]
Having a typed property (PHP 7.4+), such as:

```php
class Employee
{
    public string $name;
    public int $age;
}
```

Causes mapping operations to fail when mapping to `Employee::class`. The same mapping operating works fine if the properties are declared without types.

**Comment by mark-gerarts** [comment]
Thanks for letting me know, this breaks because typed properties without a value are not initialized internally. As a quick solution you can add a default value, e.g. `public string $name = ''`.

In the meantime I'll have to rework the `PropertyAccessor`.

**Comment by mark-gerarts** [comment]
Hi @shadowhand, the new version (1.3.11) includes a fix, let me know if you encounter any more issues!

**Comment by shadowhand** [comment]
@mark-gerarts thank you so much for the fast response!
