### ISSUE TITLE
Operation::setTo(true)

### ISSUE THREAD

**Issue by meekowhy** [mark-gerarts/automapper-plus#63]
Description of this operation says: "Always sets the property to the given value" but actually its not true - it will only set property to the given value in the target class if the source class has the same property name defined.. It doesnt make sense to me. I would like my mapper to always set given property to a given value, but I cant do it using setTo operation. Solution to this problem would be to always allow mappings for this operation \AutoMapperPlus\MappingOperation\Implementations\SetTo::canMapProperty:

    /**
     * @inheritdoc
     */
    protected function canMapProperty(string $propertyName, $source): bool
    {
        return true;
    }

**Comment by mark-gerarts** [comment]
You're right, `setTo` should not check if a property with the same name exists on the source object. Are you saying that it does not work for you this way? If so, can you provide a minimal configuration in which this occurs? For example the following configuration shows that it should in fact ignore existence of source properties:

```php
class A {}

class B {
    public $property;
}

$config = new AutoMapperConfig();
$config->registerMapping(A::class, B::class)
    ->forMember('property', Operation::setTo('some value'));

$mapper = new AutoMapper($config);

$source = new A();
$result = $mapper->map($source, B::class);

var_dump($result);
```

**Comment by meekowhy** [comment]
Hello, thank you for fast answer.. ok it seems the problem is me having older automapper version.. :- )
