### ISSUE TITLE
Support for PHP 7.4 class typed properties mapping

### ISSUE THREAD

**Issue by kamdrum** [mark-gerarts/automapper-plus#71]
The mapper doesn't map to class typed properties. Can it be somehow configured or is it not supported?

**Comment by mark-gerarts** [comment]
Hi @kamdrum, this should be supported starting from 1.3.11. If you're on this version or higher, can you show an example of it not working?

**Comment by kamdrum** [comment]
Hi @mark-gerarts, thank you for your prompt answer.
I'm on version 1.3.0 and it's marked as the latest release, so how can I update it to version 1.3.11?

**Comment by mark-gerarts** [comment]
That's weird, the latest release should be 1.3.12 ([packagist](https://packagist.org/packages/mark-gerarts/auto-mapper-plus#1.3.12)). Unless you're using the Symfony bundle? In that case an `update --with-dependencies` of the bundle should do the trick.

**Comment by kamdrum** [comment]
Thank you for your help - now it works properly :)
