### ISSUE TITLE
Possible typo In README File

### ISSUE THREAD

**Issue by ghost** [mark-gerarts/automapper-plus#73]
Checking how to create nested DTO mappings, I came across the section in the README file `Dealing with nested Mappings`. I was confused for some time with the line that reads

`$config->createMapping(Child::class, ChildDto::class);`

As far as I am aware, there doesn't seem to be a method name `createMapping`, but rather `registerMapping`. Everywhere else in the README file has the method `registerMapping`, so I tried that in my code and it works great.

I know it's small thing, but if it could be fixed, then hopefully it'll cause less confusion for people reading the docs for the library xD

**Comment by mark-gerarts** [comment]
Good catch! If you're willing to open up a PR, I'll be happy to merge it. Otherwise I'll take a look at it myself.

**Comment by ghost** [comment]
@mark-gerarts I will do that. How do I go about creating a PR since I'm not a collaborator on this repo? I just get a 403 forbidden when I try to push to a separate branch.

**Comment by mark-gerarts** [comment]
You have to fork the repo first, and add the changes on your own fork. After you've done this, a "pull request" button should appear on this repo (as per the [docs](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)).

Alternatively,I believe you can use the edit icon in the [Github UI](https://github.com/mark-gerarts/automapper-plus/blob/master/README.md), which might be easier for a quick edit.

**Comment by ghost** [comment]
@mark-gerarts created a PR https://github.com/mark-gerarts/automapper-plus/pull/77

**Comment by mark-gerarts** [comment]
Great, I merged it. Thank you for contributing!
